apps/adminpanel/urls.py
from django.conf.urls import include, url
from .views import IndexView, ParentView, AJAXChangeCategoryView, AJAXChangeSubCategoryView, AJAXChangeEmailView, AJAXChangeFacebookView, AJAXChangeTwitterView, AJAXChangeWebUrlView, AJAXChangePhoneView, AJAXCompanyActivateView


urlpatterns = [
    url(r'^moderate_children/$', IndexView.as_view(), name='index'),
    url(r'^moderate_parent/$', ParentView.as_view(), name='parent'),
    url(r'^AJAX_change_category/$', AJAXChangeCategoryView.as_view(), name='AJAX_change_category'),
    url(r'^AJAX_change_subcategory/$', AJAXChangeSubCategoryView.as_view(), name='AJAX_change_category'),
    url(r'^AJAX_change_email/$', AJAXChangeEmailView.as_view(), name='AJAX_change_email'),
    url(r'^AJAX_change_phone/$', AJAXChangePhoneView.as_view(), name='AJAX_change_phone'),
    url(r'^AJAX_change_web_url/$', AJAXChangeWebUrlView.as_view(), name='AJAX_change_web_url'),
    url(r'^AJAX_change_twitter/$', AJAXChangeTwitterView.as_view(), name='AJAX_change_twitter'),
    url(r'^AJAX_change_facebook/$', AJAXChangeFacebookView.as_view(), name='AJAX_change_facebook'),
    url(r'^AJAX_company_activate/$', AJAXCompanyActivateView.as_view(), name='AJAX_company_activate'),
]

dequr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'dequr.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('apps.adminpanel.urls', namespace='panel')),
    url(r'^', include('apps.category.urls', namespace='category')),
    url(r'^', include('apps.company.urls', namespace='company')),
    url(r'^', include('apps.complaint.urls', namespace='complaint')),
    url(r'^', include('apps.general.urls', namespace='general')),
    url(r'^', include('apps.users.urls', namespace='user')),

]
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ]

apps/adminpanel/models.py
from django.db import models

# Create your models here.

apps/adminpanel/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View
from apps.company.models import (Company, SubCompany)
from apps.category.models import (Category, SubCategory)


class AJAXCompanyActivateView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            company = Company.objects.get(id=company_id)
            company.is_approved = True
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AJAXChangeFacebookView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            facebook_string = request.GET.get('facebook', None)
            company = Company.objects.get(id=company_id)
            company.facebook = facebook_string
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AJAXChangeTwitterView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            twitter_string = request.GET.get('twitter', None)
            company = Company.objects.get(id=company_id)
            company.twitter = twitter_string
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AJAXChangeWebUrlView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            web_url_string = request.GET.get('web_url', None)
            company = Company.objects.get(id=company_id)
            company.web_url = web_url_string
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AJAXChangePhoneView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            phone_string = request.GET.get('phone', None)
            company = Company.objects.get(id=company_id)
            company.phone = phone_string
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AJAXChangeEmailView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            email_string = request.GET.get('email', None)
            company = Company.objects.get(id=company_id)
            company.email = email_string
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AJAXChangeSubCategoryView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            category_id = request.GET.get('category', None)
            company = Company.objects.get(id=company_id)
            subcategory = SubCategory.objects.get(id=category_id)
            company.subcategory = subcategory
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AJAXChangeCategoryView(View):
    def get(self, request,  *args, **kwargs):
        #if request.is_ajax():
        if True:
            company_id = request.GET.get('company', None)
            category_id = request.GET.get('category', None)
            company = Company.objects.get(id=company_id)
            category = Category.objects.get(id=category_id)
            company.category = category
            company.subcategory = None
            company.save()
            data = {}
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class ParentView(View):
    def get(self, request,  *args, **kwargs):
        company = Company.objects.all().filter(is_approved=False)
        category = Category.objects.all()
        subcategory = SubCategory.objects.all()
        return render(request, 'adminpanel/parent.html', {
                               'companys': company, 'categorys': category,
                               'subcategorys': subcategory, })


class IndexView(View):
    def get(self, request,  *args, **kwargs):

        if request.is_ajax():
            if request.GET.get('delete_child', None):
                subcompany_id = request.GET.get('delete_child', None)
                child = SubCompany.objects.get(id=subcompany_id)
                child.delete()
                data = {}
                mimetype = 'application/json'
                return HttpResponse(data, mimetype)

            if request.GET.get('convert_to_father', None):
                subcompany_id = request.GET.get('convert_to_father', None)
                child = SubCompany.objects.get(id=subcompany_id)
                parent = Company(name=child.name)
                parent.save()
                child.delete()
                results = []
                for company in Company.objects.all():
                    company_json = {}
                    company_json['id'] = company.id
                    company_json['name'] = company.name
                    results.append(company_json)
                data = json.dumps(results)
                mimetype = 'application/json'
                return HttpResponse(data, mimetype)

            if request.GET.get('checkbox_masive', None) and \
               request.GET.get('select_masive', None):
                company_id = request.GET.get('select_masive', None)
                subcompany_ids = request.GET.get('checkbox_masive', None)
                subcompany_ids = subcompany_ids.split(",")
                parent = Company.objects.get(id=company_id)
                for x in subcompany_ids:
                    child = SubCompany.objects.get(id=x)
                    child.company = parent
                    child.save()
                data = {}
                mimetype = 'application/json'
                return HttpResponse(data, mimetype)

            if request.GET.get('create_fahter', None):
                q = request.GET.get('create_fahter', None)
                if not Company.objects.filter(name=q).exists():
                    parent = Company(name=q)
                    parent.save()
                results = []
                for company in Company.objects.all():
                    company_json = {}
                    company_json['id'] = company.id
                    company_json['name'] = company.name
                    results.append(company_json)
                data = json.dumps(results)
                mimetype = 'application/json'
                return HttpResponse(data, mimetype)

            if request.GET.get('search', None):
                q = request.GET.get('search', None)
                subcompanys = SubCompany.objects.all().filter(company=None)
                subcompanys = subcompanys.filter(name__icontains=q)
                results = []
                for subcompany in subcompanys:
                    subcompany_json = {}
                    subcompany_json['id'] = subcompany.id
                    subcompany_json['name'] = subcompany.name
                    results.append(subcompany_json)

                results2 = []
                for company in Company.objects.all():
                    company_json = {}
                    company_json['id'] = company.id
                    company_json['name'] = company.name
                    results2.append(company_json)
                final = {'q': results, 'company': results2}
                data = json.dumps(final)
                mimetype = 'application/json'
                return HttpResponse(data, mimetype)
        else:
            company = Company.objects.all()
            subcompany = SubCompany.objects.all().filter(company=None)
            companys_count = subcompany.count()
            subcompany = subcompany[:100]
            return render(request, 'adminpanel/inicio.html', {
                'subcompanys': subcompany, 'companys_count': companys_count,
                'companys': company, })

templates/adminpanel/inicio.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block content %}

<div id="wrapgeneral" class="mt-large">
	<div class="container">
		<div class="row">
			<div id="main" class="col-md-8">
			<table class="table">
					<tbody>
						<tr>
							<!--<th scope="row">{{forloop.counter}}</th>
							<th><label><input name="hide_asignadas" type="checkbox"/> Sin asignadas <small class="hint">({{companys_count}})</small></label></th>-->
							<th><input type="text" id="search" placeholder="Buscar empresas similares [...]"></th>
							<th>
								<select id="select_masive">
									<option selected="selected">---------</option>
									{% for company in companys %}
									<option value="{{company.id}}">{{company.name}}</option>
									{% endfor %}
								</select>
							</th>
							<th><a href="#" class="asign_masive btn btn-inline btn-small btn-primary mb-small"><i class="fa fa-check"></i></a></th>
						</tr>
						<tr>
							<th><input type="text" id="create_fahter" placeholder="Crear un nuevo padre"></th>
							<th><a href="#" class="create_fahter btn btn-inline btn-small btn-primary mb-small"><i class="fa fa-check"></i></a></th>
						</tr>
					</tbody>
				</table>
				
				<table class="table table-hover">
					<thead>
						<tr>
							<th><input name="all_select" type="checkbox"/></th>
							<th>Nombre</th>
							<th>Selecionar un Padre</th>
							<th>Convertir en Padre</th>
							<th>Eliminar</th>
						</tr>
					</thead>
					<tbody class="companys">
						{% for subcompany in subcompanys %}
						<tr>
							<th><input id="{{subcompany.id}}" class="this" name="this" type="checkbox"/></th>
							<td>{{subcompany.name}}</td>
							<td>
								<select id="{{subcompany.id}}">
									<option selected="selected">---------</option>
									{% for company in companys %}
									<option value="{{company.id}}">{{company.name}}</option>
									{% endfor %}
								</select>
							</td>
							<td class="txt-c"><a href="#" id="{{subcompany.id}}" class="convert_to_father btn btn-inline btn-small btn-primary mb-small"><i class="fa fa-check"></i></a></td>
							<td class="txt-c"><a href="#" id="{{subcompany.id}}" class="delete_child btn btn-inline btn-small btn-danger mb-small"><i class="fa fa-trash-o"></i></a></td>
						</tr>
						{% endfor %}

					</tbody>
				</table>
				<script type="text/javascript">
					$(document).ready(function() {
						//
						$('a.create_fahter').click(function() {
							var q = $('#create_fahter').val();
							$.ajax({
								url: '{% url "panel:index" %}',
								data: {'create_fahter': q},
								type: 'get',
								success: function(data) {
									$("option").remove();
									$("select").append('<option selected="selected">---------</option>');
									for (var i = 0; i < data.length; i++) {
										$("select").append('<option value="'+data[i].id+'">'+data[i].name+'</option>');
									}
									$('#create_fahter').val("");
								}
							});
						});
						//
						$('a.asign_masive').click(function() {
							var checkbox_masive = "";
							$('.this:checked').each(function() {
							    checkbox_masive += $(this).attr('id')+',';
								$(this).parents("tr").remove();
							});
							checkbox_masive = checkbox_masive.substring(0,checkbox_masive.length-1);

							var select_masive = $('#select_masive option:selected').val();
							$('#select_masive').val("---------");


							if ((select_masive != "---------") & (checkbox_masive.length > 0)) {
								$.ajax({
									url: '{% url "panel:index" %}',
									data: {'checkbox_masive': checkbox_masive, 'select_masive':select_masive,},
									type: 'get',
									success: function(data) {
									}
								});
							}
						});
						//
						$('#search').keyup(function(e) {
						    var q = $(this).val();
						    if(e.which == 13) {
						    	$(this).val("");
							    $.ajax({
									url: '{% url "panel:index" %}',
									data: {'search': q},
									type: 'get',
									success: function(data) {
										html = '<option selected="selected">---------</option>';
										html2 = '';
										for (var i = 0; i < data.company.length; i++) {
											html += '<option value="'+data.company[i].id+'">'+data.company[i].name+'</option>';
										};
										for (var i = 0; i < data.q.length; i++) {
											html2 += '<tr> <th><input id="'+data.q[i].id+'" class="this" name="this" type="checkbox"/></th> <td>'+data.q[i].name+'</td> <td> <select id="'+data.q[i].id+'"> '+html+' </select> </td> <td class="txt-c"><a href="#" id="'+data.q[i].id+'" class="convert_to_father btn btn-inline btn-small btn-primary mb-small"><i class="fa fa-check"></i></a></td> <td class="txt-c"><a href="#" id="'+data.q[i].id+'" class="delete_child btn btn-inline btn-small btn-danger mb-small"><i class="fa fa-trash-o"></i></a></td></tr>';
										}
										$('.companys').html(html2);
									}
								});
						    }
						});


						$('input[name="all_select"]').click(function() {  
					        if(this.checked) {
					            $('.this').prop('checked', true);
					        } else {  
					            $('.this').prop('checked', false);
					        }
					        
					    }); 

						// Borrar a sub
						$('a.delete_child').change(function() {
							var element = $(this).parents("tr").remove();
							var id = $(this).attr("id");

							
						});
						// Convertir a padre
						$('a.convert_to_father').click(function() {
							var element = $(this).parents("tr").remove();
							var id = $(this).attr("id");
							$.ajax({
								url: '{% url "panel:index" %}',
								data: {'convert_to_father': id},
								type: 'get',
								success: function(data) {
									$("option").remove();
									$("select").append('<option selected="selected">---------</option>');
									for (var i = 0; i < data.length; i++) {
										$("select").append('<option value="'+data[i].id+'">'+data[i].name+'</option>');
									}
								}
							});
						});
						//
						$('input[name="hide_asignadas"]').change(function() {
						    if(this.checked) {
								$.ajax({
									url: '{% url "panel:index" %}',
									data: {'hide_asignadas': '1'},
									type: 'get',
									success: function(data) {
										console.log(data);
									}
								});
						    } else {
								$.ajax({
									url: '{% url "panel:index" %}',
									data: {'hide_asignadas': '0'},
									type: 'get',
									success: function(data) {
										//console.log(data);
									}
								});
						    }
						});

					});

					
				</script>

			</div>
			<!-- main -->

			<div id="sidebar-left"class="col-md-4">

				<div class="complaint-box">
					<div class="content">
						<ol class="list">
                            <li class="item-box">
                                <a href='{% url "panel:index" %}'>
                                    <i class="fa fa-edit"></i>
                                    <p class="content">Moderar hijos</p>
                                </a>
                            </li>
                        </ol>
					</div>
				</div>

			</div>
			<!-- sidebar-left -->

		</div>
		<!-- row -->
	</div>
	<!-- container -->
</div>

{% endblock %}

templates/adminpanel/parent.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block content %}

<div id="wrapgeneral" class="mt-large">
	<div class="container">
		<div class="row">
			<div id="main" class="col-md-12">
			<!--<table class="table">
					<tbody>
						<tr>
							<th><input type="text" id="search" placeholder="Buscar empresas similares [...]"></th>
						</tr>
					</tbody>
				</table>-->
				
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Category</th>
							<th>SubCategory</th>
							<th>Email</th>
							<th>Telefono</th>
							<th>Url</th>
							<th>Twitter</th>
							<th>Facebook</th>
							<th>Aprovada</th>
						</tr>
					</thead>
					<tbody class="companys">
						{% for company in companys %}
						<tr>
							<td><input type="text" name="name" value="{{company.name}}" /></td>
							<td>
								<select class="categorys" company="{{company.id}}">
									{% if company.category %}
										<option>---------</option>
									{% else %}
										<option selected="selected">---------</option>
									{% endif %}
									{% for category in categorys %}
										{% if company.category == category %}
											<option selected="selected" value="{{category.id}}">{{category.name}}</option>
										{% else %}
											<option value="{{category.id}}">{{category.name}}</option>
										{% endif %}
									{% endfor %}
								</select>
							</td>
							<td>
								{% if company.subcategory %}
								<input type="hidden" value="{{company.subcategory.id}}">
								{% else %}
								<input type="hidden" value="-1">
								{% endif %}
								<select  company="{{company.id}}" class="subc subcategorys-{{company.id}}">
									<option selected="selected">---------</option>
								</select>
							</td>
							<td><input type="text" company="{{company.id}}" name="email" value="{{company.email}}" /></td>
							<td><input type="text" company="{{company.id}}" name="phone" value="{{company.phone}}" /></td>
							<td><input type="text" company="{{company.id}}" name="web_url" value="{{company.web_url}}" /></td>
							<td><input type="text" company="{{company.id}}" name="twitter" value="{{company.twitter}}" /></td>
							<td><input type="text" company="{{company.id}}" name="facebook" value="{{company.facebook}}" /></td>
							<td>
							{% if company.is_approved %}
								<a href="#" company="{{company.id}}" class="btn btn-inline btn-small btn-danger mb-small">Desactivar</a>
							{% else %}
								<a href="#" company="{{company.id}}" class="activate btn btn-inline btn-small btn-primary mb-small">Activar</a>
							{% endif %}
							</td>
							
						</tr>
						{% endfor %}

					</tbody>
				</table>
				<script type="text/javascript">
					$(document).ready(function() {

						$('.categorys').each(function() {
							if ($(this).val() != "---------") {
								category = $(this).val();
								company = $(this).attr("company");
								var html = '<option selected="selected">---------</option>';
								$.ajax({
									url: '/ajax_load_subcategory/',
									data: {'term':category},
									type: 'get',
									success: function(data) {
										
										for (var i = 0, len = data.length; i < len; ++i) {
											html += '<option value="' + data[i]['id'] + '">' + data[i]['name'] + '</option>';
										} 
										$('.subcategorys-'+company).html(html);
										select = $('.subcategorys-'+company).siblings('input[type="hidden"]').val();
										if (select != -1) {
											$('.subcategorys-'+company).val(select);
										}
									},
								});
							}
						});

						$('.categorys').change(function() {
							var select = $(this).val();
							var company = $(this).attr("company")
							var html = '<option selected="selected">---------</option>';
							if (select != "---------") {
								$.ajax({
									url: '/ajax_load_subcategory/',
									data: {'term':select},
									type: 'get',
									success: function(data) {
										
										for (var i = 0, len = data.length; i < len; ++i) {
											html += '<option value="' + data[i]['id'] + '">' + data[i]['name'] + '</option>';
										} 
										$('.subcategorys-'+company).html(html);

									},
								});

								$.ajax({
									url: '/AJAX_change_category/',
									data: {'company':company, 'category':select},
									type: 'get',
									success: function(data) {
									},
								});

							} else{
								$('.subcategorys-'+company).html(html);
							}
						});

						$('.subc').change(function() {
							var select = $(this).val();
							var company = $(this).attr("company")
							var html = '<option selected="selected">---------</option>';
							if (select != "---------") {
								$.ajax({
									url: '/AJAX_change_subcategory/',
									data: {'company':company, 'category':select},
									type: 'get',
									success: function(data) {
									},
								});
							} else{
								$('.subcategorys-'+company).html(html);
							}
						});

						$('input[name="email"]').keyup(function(e) {
						    var q = $(this).val();
						    var company = $(this).attr("company");
						    if(e.which == 13) {
						    	//$(this).val("");
							    $.ajax({
									url: '/AJAX_change_email/',
									data: {'company':company, 'email': q},
									type: 'get',
									success: function(data) {
									}
								});
						    }
						});

						$('input[name="phone"]').keyup(function(e) {
						    var q = $(this).val();
						    var company = $(this).attr("company");
						    if(e.which == 13) {
						    	//$(this).val("");
							    $.ajax({
									url: '/AJAX_change_phone/',
									data: {'company':company, 'phone': q},
									type: 'get',
									success: function(data) {
									}
								});
						    }
						});

						$('input[name="web_url"]').keyup(function(e) {
						    var q = $(this).val();
						    var company = $(this).attr("company");
						    if(e.which == 13) {
						    	//$(this).val("");
							    $.ajax({
									url: '/AJAX_change_web_url/',
									data: {'company':company, 'web_url': q},
									type: 'get',
									success: function(data) {
									}
								});
						    }
						});

						$('input[name="twitter"]').keyup(function(e) {
						    var q = $(this).val();
						    var company = $(this).attr("company");
						    if(e.which == 13) {
						    	//$(this).val("");
							    $.ajax({
									url: '/AJAX_change_twitter/',
									data: {'company':company, 'twitter': q},
									type: 'get',
									success: function(data) {
									}
								});
						    }
						});

						$('input[name="facebook"]').keyup(function(e) {
						    var q = $(this).val();
						    var company = $(this).attr("company");
						    if(e.which == 13) {
						    	//$(this).val("");
							    $.ajax({
									url: '/AJAX_change_facebook/',
									data: {'company':company, 'facebook': q},
									type: 'get',
									success: function(data) {
									}
								});
						    }
						});

						$('a.activate').click(function() {
							var company = $(this).attr("company");
							console.log(company);
							$.ajax({
								url: '/AJAX_company_activate/',
								data: {'company':company, },
								type: 'get',
								success: function(data) {
								}
							});
						});
						

					});
				</script>

			</div>
			<!-- main -->

		</div>
		<!-- row -->
	</div>
	<!-- container -->
</div>

{% endblock %}