apps/category/urls.py
from django.conf.urls import include, url


urlpatterns = [
    #url(r'^category/(?P<slug>[-\w]+)/$', CategoryView.as_view(), name='category'),
]

apps/company/urls.py
from django.conf.urls import include, url
from .views import (CategoryView, CategorysView)


urlpatterns = [
    url(r'^categorys/$', CategorysView.as_view(), name='categorys'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryView.as_view(), name='category'),
]

dequr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'dequr.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('apps.adminpanel.urls', namespace='panel')),
    url(r'^', include('apps.category.urls', namespace='category')),
    url(r'^', include('apps.company.urls', namespace='company')),
    url(r'^', include('apps.complaint.urls', namespace='complaint')),
    url(r'^', include('apps.general.urls', namespace='general')),
    url(r'^', include('apps.users.urls', namespace='user')),

]
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ]

apps/category/models.py
from django.db import models
from django.template.defaultfilters import slugify

class Category(models.Model):
    name = models.CharField(max_length=140, unique=True)
    image = models.ImageField(upload_to="category_logos", blank=True)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class SubCategory(models.Model):
    category = models.ForeignKey(Category, null=True, blank=True)
    name = models.CharField(max_length=140, unique=True)
    image = models.ImageField(upload_to="subcategory_logos", blank=True)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(SubCategory, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

apps/company/models.py
from django.db import models
from apps.category.models import Category, SubCategory


class Company(models.Model):
    category = models.ForeignKey(Category, null=True, blank=True)
    subcategory = models.ForeignKey(SubCategory, null=True, blank=True)
    name = models.CharField(max_length=140, unique=True)
    image = models.ImageField(upload_to="company_logos", blank=True)
    email = models.EmailField(max_length=140, blank=True)
    is_approved = models.BooleanField(default=False, blank=True)
    phone = models.CharField(max_length=140, blank=True)
    web_url = models.CharField(max_length=140, blank=True)
    facebook = models.CharField(max_length=140, blank=True)
    twitter = models.CharField(max_length=140, blank=True)

    def __unicode__(self):
        return self.name


class SubCompany(models.Model):
    company = models.ForeignKey(Company, null=True, blank=True)
    name = models.CharField(max_length=140)

    def __unicode__(self):
        return self.name

apps/category/views.py
from django.shortcuts import render

# Create your views here.

apps/company/views.py
# -*- coding: utf-8 -*-
from django.http import Http404
from django.shortcuts import render
from django.views.generic import View
from apps.category.models import Category, SubCategory


class CategorysView(View):
    def get(self, request,  *args, **kwargs):
        ul = []
        for cat in Category.objects.all():
            if SubCategory.objects.filter(category=cat).count() > 0:
                q = SubCategory.objects.filter(category=cat).order_by('name')
                for item in q:
                    li = {
                        'category': cat.name,
                        'cat_slug': cat.slug,
                        'sub_category': item.name,
                        'sub_slug': item.slug,
                    }
                    ul.append(li)
            else:
                li = {
                    'category': cat.name,
                    'cat_slug': cat.slug,
                    'sub_category': "",
                    'sub_slug': "",
                }
                ul.append(li)
        return render(request, 'company/all_category.html', {'categorys': ul, })


class CategoryView(View):
    def get(self, request, slug=None,  *args, **kwargs):
        print slug
        if slug:
            if Category.objects.filter(slug=slug).exists():
                li = Category.objects.get(slug=slug,)
                return render(request, 'company/single_category.html', {
                    'data': li, })
            elif SubCategory.objects.filter(slug=slug).exists():
                li = SubCategory.objects.get(slug=slug,)
                return render(request, 'company/single_category.html', {
                    'data': li, })
            else:
                raise Http404
        else:
            raise Http404

templates/company/all_category.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&appId=731623136870740&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="wrapgeneral">
    <div class="container">
        <div class="row">
            <div class="single_header txt-c col-md-12">
                
                {% regroup categorys|dictsort:"category" by category as categorys %}
                
                <div class="top">
                    
                    {% for category in categorys %}
                    {% if forloop.counter == 1 or forloop.counter == 4 or forloop.counter == 7 or forloop.counter == 10 or forloop.counter == 13 or forloop.counter == 16 or forloop.counter == 19 or forloop.counter == 22 %}
                    <div class="row mb-xlarge">
                    {% endif %}

                        <div class="col-md-4">
                            <ul class="categorys-list">
                                {% for li in category.list %}
                                {% if forloop.counter == 1 %}
                                <li class="title"><a href="{% url 'company:category' li.cat_slug %}">{{category.grouper}} </a></li>
                                {% endif %}
                                <li><a href="{% url 'company:category' li.sub_slug %}">{{li.sub_category}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>

                    {% if forloop.counter == 3 or forloop.counter == 6 or forloop.counter == 9 or forloop.counter == 12 or forloop.counter == 15 or forloop.counter == 18 or forloop.counter == 21 or forloop.counter == 24 %}
                    </div>
                    {% endif %}
                    
                    {% endfor %}
                </div>
            </div>
        </div>



    </div>
    <!-- row -->
</div>
<!-- container -->
</div>
{% endblock %}