apps/company/urls.py
from django.conf.urls import include, url
from .views import (CategoryView, CategorysView)


urlpatterns = [
    url(r'^categorys/$', CategorysView.as_view(), name='categorys'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryView.as_view(), name='category'),
]

apps/users/urls.py
from django.conf.urls import include, url
from .views import LoginIndex, LogoutView, RequiredEmailView, SettingView,SettingBissView, MyCommentsView, MyComplaintView


urlpatterns = [
    url(r'^login_o_registro/$', LoginIndex.as_view(), name='index'),
    url(r'^required_email/$', RequiredEmailView.as_view(), name='required_email'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    url(r'^setting/$', SettingView.as_view(), name='setting'),
    url(r'^setting_biss/$', SettingBissView.as_view(), name='setting_biss'),
    url(r'^my_comments/$', MyCommentsView.as_view(), name='my_comments'),
    url(r'^my_complaints/$', MyComplaintView.as_view(), name='my_complaints'),

]

dequr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'dequr.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('apps.adminpanel.urls', namespace='panel')),
    url(r'^', include('apps.category.urls', namespace='category')),
    url(r'^', include('apps.company.urls', namespace='company')),
    url(r'^', include('apps.complaint.urls', namespace='complaint')),
    url(r'^', include('apps.general.urls', namespace='general')),
    url(r'^', include('apps.users.urls', namespace='user')),

]
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ]

templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
    <meta content="text/html" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="True" name="HandheldFriendly">
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <title>Home</title>

        {% load static from staticfiles %}

        <link rel="shortcut icon" href="themes/r4/favicon-01.png">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'assets/css/defaults.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/system.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    </head>
    <body>

        <div id="header">
            <div id="header-container">
                <div class="row">
                    <div class="col-sm-8 col-xs-6 hide-overflow">
                        <ul class="navegacion">
                            <li class="mr-large">
                                <a href="{% url 'general:index' %}" class="logo">
                                    <img style="width: 180px;padding: 5px 0;" src="{% static 'assets/img/dequr_megafono.png' %}" alt="" title="">
                                </a>
                            </li>
                            <li class="mr-small hidden-xs">
                                <a href="#"><i class="fa fa-file-text-o mrxxs"></i>Quejas</a>
                            </li>
                            <li class="mr-small hidden-xs">
                                <a href="{% url 'company:categorys' %}"><i class="fa fa-folder-open mrxxs"></i>Categorias</a>
                            </li>
                            <li class="mr-small hidden-xs">
                                <a href="{% url 'user:index' %}"><i class="fa fa-book mrxxs"></i>Blog</a>
                            </li>
                            <!--<li class="mt-large mr-small hidden-xs hidden-sm">
                                <form  id="global-search" action="/search">
                                    <label for="filter-by"><i class="fa fa-search"></i></label>
                                    <input name="q" type="search" placeholder="Buscar">
                                </form>
                            </li>-->
                        </ul>
                    </div>
                    <div class="col-sm-4 col-xs-6">
                        <ul class="navegacion" style="text-align: right;">
                            <li style="height: 52px;"></li>
                            {% if user.is_authenticated %}
                            <li class="mr-small hidden-xs">
                                <a href="{% url 'user:logout' %}">{{user.first_name}} {{user.last_name}}</a>
                            </li>
                            {% else %}
                            <li class="mr-small hidden-xs">
                                <a href="{% url 'user:index' %}"><i class="fa fa-user mrxxs"></i>Iniciar sesión</a>
                            </li>
                            <li class="mr-small hidden-xs">
                                <a href="#"><i class="fa fa-suitcase mrxxs"></i>Para Empresas</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>

                </div>
            </div>
            <!-- header-container -->
        </div>
        <div id="ads-720-90" style="padding: 10px 0; background: #eee; width: 100%; overflow-x: hidden; line-height: 1;">
            <div class="row">
                <div class="col-sm-12 txt-c">
                    <img src="https://lh6.ggpht.com/41LFWBytPnxKsfZf6mivs6ba7qdOBtfk9-7MzWSMqwC3IFOvaXd8rejFiyeXKfBOK16mMEopeA=w728" alt="">
                </div>
            </div>
        </div>


        {% block content %}{% endblock %}

        

        <!-- wrappergeneral -->
        <div class="footer">
            <div class="container">
                <div class="footer-inner row">
                    <div class="col-sm-4">
                        <h3>Nosotros</h3>
                        <ul>
                            <li><a href="">Acerca de Dequr.com</a></li>
                            <li><a href="">Noticias</a></li>
                            <li><a href="">En los medios</a></li>
                            <li><a href="">Blog</a></li>
                            <li><a href="">Preguntas Frecuentes</a></li>
                            <li><a href="">Políticas de Privacidad</a></li>
                            <li><a href="">Términos de Uso</a></li>
                            <li><a href="">Contacto</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4">
                        <h3>Servicios</h3>
                        <ul>
                            <li><a href="">Soluciones para Empresas</a></li>
                            <li><a href="">Tips para Consumidores</a></li>
                            <li><a href="">Formatos de Quejas</a></li>
                            <li><a href="">Correos Spam</a></li>
                            <li><a href="">Denuncias Grupales</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4">
                        <h3>Encuentra</h3>
                        <ul>
                            <li><a href="">Compañías</a></li>
                            <li><a href="">Quejas</a></li>
                            <li><a href="">Quejas Promocionadas</a></li>
                            <li><a href="">Categorías</a></li>
                            <li><a href="">Compañías con más Quejas</a></li>
                            <li><a href="">¿Algún error? Informanos aquí</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        
        <script src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>
        <script src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
        <script src="http://malsup.github.com/min/jquery.form.min.js"></script>

        <script src="{% static 'assets/js/jquery.geocomplete.min.js' %}"></script>
        
        <script src="{% static 'assets/js/script.js' %}"></script>
    </body>
</html>