apps/complaint/urls.py
from django.conf.urls import include, url
from .views import (IndexView,CreateComplaintLastStepView,ProfileView,\
    AjaxCompany,AjaxLoadCategoryFromAutocompleteCompany,AjaxLoadSubCategory,\
    CreateComplaintStepOneWizard,MultiUploadAjax,CreateComplaintFinishView,\
    FORMS)

urlpatterns = [
    url(r'^single_page/$', IndexView.as_view(), name='index'),
    # url(r'^post_page/$', PostView.as_view(), name='create'),
    #url(r'^post_page_step_one/$', StepOneView.as_view(), name='post_step_one_complaint'),
    
    url(r'^profile/$', ProfileView.as_view(), name='profile'),


    #Wizard Create
    url(r'^create_complaint/$', CreateComplaintStepOneWizard.as_view(FORMS, condition_dict={'cc': 0}), name='create'),
    url(r'^create_complaint_last_step/$', CreateComplaintLastStepView.as_view(), name='create_complaint_last_step'),
    url(r'^complaint_finish/$', CreateComplaintFinishView.as_view(), name='complaint_finish'),


    #Autocompletar ajax 
    url(r'^ajax_multiupload/$', MultiUploadAjax.as_view(), name='ajax_multiupload'),
    url(r'^ajax_company/$', AjaxCompany.as_view(), name='ajax_company'),
    url(r'^ajax_load_category_from_autocomplete_company/$', AjaxLoadCategoryFromAutocompleteCompany.as_view()),
    url(r'^ajax_load_subcategory/$', AjaxLoadSubCategory.as_view()),
]

dequr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'dequr.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('apps.adminpanel.urls', namespace='panel')),
    url(r'^', include('apps.category.urls', namespace='category')),
    url(r'^', include('apps.company.urls', namespace='company')),
    url(r'^', include('apps.complaint.urls', namespace='complaint')),
    url(r'^', include('apps.general.urls', namespace='general')),
    url(r'^', include('apps.users.urls', namespace='user')),

]
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ]

apps/complaint/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Complaint, ItemFiles


class CreateComplaintStepTwoForm(forms.Form):

    # Contacto
    complete_name = forms.CharField(max_length=140, required=False, widget=forms.TextInput(attrs={"placeholder": "Nombre completo"}))
    email = forms.EmailField(max_length=140, required=False, widget=forms.TextInput(attrs={"placeholder": "Correo electrónico"}))
    cellphone = forms.CharField(max_length=140, required=False, widget=forms.TextInput(attrs={"placeholder": "Telefono"}))
    
    # Localizacion
    place = forms.CharField(max_length=140, required=False, widget=forms.TextInput(attrs={"placeholder": "Lugar"}))
    product_or_service = forms.CharField(max_length=140, required=False, widget=forms.TextInput(attrs={"placeholder": "Producto o servicio"}))
    other_solution = forms.CharField(max_length=140, required=False)

    CHOICES = [
                (0, 'Que me proponga una solucion'),
                (1, 'La devolucion de mi Dinero'),
                (2, 'Que entregue mi producto'),
                (3, 'Otra solucion'),
            ]

    actions_radio = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES, required=False)

class CreateComplaintStepOneForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateComplaintStepOneForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "Título de tu queja"
        self.fields['description'].widget.attrs['placeholder'] = "Descripcion de tu queja"
        self.fields['company'].widget.attrs['placeholder'] = "Nombre de la empresa"

    company = forms.CharField(max_length=140, )
    company_val = forms.CharField(max_length=140, widget=forms.HiddenInput(), required=False)
    terms = forms.BooleanField(required=False)

    class Meta:
        model = Complaint
        fields = "__all__"
        exclude = ['date_create', 'company', 'ipv4', 'audio', 'video']

    def clean_terms(self):
        if not self.cleaned_data["terms"]:
            raise forms.ValidationError(
                "Para publicar debe aceptar nuestros terminos del servicio."
            )        
    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError("El Correo electrónico ya se encuentra registrado")
        return self.cleaned_data['email']

class AjaxUploadForm(forms.ModelForm):
    class Meta:
        model = ItemFiles
        fields = "__all__"

apps/users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.users.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginTraditionalForm(forms.Form):
    username = forms.CharField(max_length=140, required=True)
    password = forms.CharField(max_length=140, required=True, widget=forms.TextInput(attrs={'type':'password'}))
    form = forms.CharField(required=False,widget=forms.TextInput(attrs={'type':'hidden','value':'login'}))
    
class UserCreateForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = "Username"
        self.fields['email'].widget.attrs['placeholder'] = "Correo electrónico"
        self.fields['password1'].widget.attrs['placeholder'] = "Contraseña"
        self.fields['password2'].widget.attrs['placeholder'] = "Confirmación"

    email = forms.EmailField(required=True)
    form = forms.CharField(required=False,widget=forms.TextInput(attrs={'type':'hidden','value':'register'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        exclude = ['first_name', 'last_name']

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError("El Correo electrónico ya se encuentra registrado")
        return self.cleaned_data['email']

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

apps/complaint/views.py
# -*- coding: utf-8 -*-
import json
import ast
from dequr import settings
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from apps.company.models import Company, SubCategory, Category
from apps.complaint.models import Complaint, ComplaintContact, ComplaintLocation, ComplaintRequest, ItemFiles
from formtools.wizard.views import SessionWizardView
from .forms import CreateComplaintStepOneForm, CreateComplaintStepTwoForm, AjaxUploadForm
from django.core.files.storage import FileSystemStorage
from dequr import settings
from django.core.urlresolvers import reverse
from apps.users.forms import LoginTraditionalForm, UserCreateForm
from django.contrib.auth import login, authenticate


class IndexView(View):
    def get(self, request,  *args, **kwargs):
        return render(request, 'complaint/single_page.html')


class ProfileView(View):
    def get(self, request,  *args, **kwargs):
        return render(request, 'complaint/profile.html')


FORMS = [("0", CreateComplaintStepOneForm),("1", CreateComplaintStepTwoForm),]
class CreateComplaintStepOneWizard(SessionWizardView):
    TEMPLATES = {
                    "0": "complaint/create_complaint_step_one.html",
                    "1": "complaint/create_complaint_step_two.html",
                }

    def get_context_data(self, form, **kwargs):
        context = super(CreateComplaintStepOneWizard, self).get_context_data(form=form, **kwargs)
        if self.steps.current == '0':
            context.update({'image_tmp': self.request.session.get("image_tmp", None), })

            try:
                del self.request.session['form_data']
            except KeyError:
                pass
            try:
                del self.request.session['image_tmp']
            except KeyError:
                pass

        elif self.steps.current == '1':
            aux = self.get_cleaned_data_for_step("0")['company']
            context.update({'company': aux, })
        return context

    def get_template_names(self):
        return [self.TEMPLATES[self.steps.current]]

    def done(self, form_list, **kwargs):
        # Salvamos los forms y guardamos en una session
        form_data = [form.cleaned_data for form in form_list]
        #print form_data
        try:
            form_data[0]["category"] = form_data[0]["category"].id
        except AttributeError:
            form_data[0]["category"] = None

        try:
            form_data[0]["subcategory"] = form_data[0]["subcategory"].id
        except AttributeError:
            form_data[0]["subcategory"] = None

        self.request.session['form_data'] = form_data
        return redirect(reverse("complaint:create_complaint_last_step"))


class CreateComplaintLastStepView(View):

    def get(self, request,  *args, **kwargs):
        if request.session.get("form_data", None):
            ##
            # Publicar como aninimo o como usuario
            ##
            if request.session.get("invited", None) or request.user.is_authenticated():
                i=0
                form_list = self.request.session['form_data']
                for form in form_list:

                    #Procesamos los 2 formularios
                    if i==0:
                        #Get category
                        try:
                            form["category"] = Category.objects.get(id=form["category"])
                        except Category.DoesNotExist:
                            form["category"] = None

                        #Get subcategory si no None
                        try:
                            form["subcategory"] = SubCategory.objects.get(id=form["subcategory"])
                        except SubCategory.DoesNotExist:
                            form["subcategory"] = None

                        #Get company si no la crea
                        try:
                            if form["company_val"]:
                                company = Company.objects.get(id=form["company_val"])
                            else:
                                company = Company.objects.get(name__icontains=form["company"])
                        except Company.DoesNotExist:
                            company = Company(name=form["company"], category=form["category"], subcategory=form["subcategory"])
                            company.save()

                        # Get de la ip del usuario
                        ip = request.META.get('REMOTE_ADDR')

                        complaint = Complaint(title=form["title"],
                                                description=form["description"],
                                                company=company,
                                                category=form["category"],
                                                subcategory=form["subcategory"],
                                                ipv4=ip,
                                                )
                        ##
                        # Publicar como usuario si esta conectado
                        ##
                        if request.user.is_authenticated():
                           complaint.user = request.user

                        #Guardamos la instancia
                        complaint.save()
                    elif i==1:
                        complaint_contact = ComplaintContact(complaint=complaint,
                                                                complete_name=form["complete_name"],
                                                                email=form["email"],
                                                                cellphone=form["cellphone"],)
                        complaint_location = ComplaintLocation(complaint=complaint,
                                                                place=form["place"],
                                                                product_or_service=form["product_or_service"],
                                                                other_solution=form["other_solution"],)
                        complaint_request = ComplaintRequest(complaint=complaint, actions_radio=form["actions_radio"],)

                        # Guardamos la instancia
                        complaint_contact.save()
                        complaint_location.save()
                        complaint_request.save()

                        if request.session.get("image_tmp", None) and request.session.get("image_tmp", None)!=[]:
                            for x in request.session['image_tmp']:
                                #Get ItemFiles si no None
                                try:
                                    item_object = ItemFiles.objects.get(id=x['id'])
                                except ItemFiles.DoesNotExist:
                                    item_object = None

                                if item_object:
                                    item_object.complaint=complaint
                                    item_object.save()
                    i=i+1

                #Al terminar ir a la url
                return redirect(reverse("complaint:complaint_finish"))
            else:
                login_error = None
                login_form = LoginTraditionalForm()
                register_form = UserCreateForm()
                return render(request, 'complaint/create_complaint_last_step.html',{
                    "company": self.request.session['form_data'][0]["company"],
                    'login_form':login_form,
                    'register_form':register_form, 'login_error':login_error,
                    })
        else:
            #Error 404
            return redirect("/")

    def post(self, request,  *args, **kwargs):
        login_error = None
        login_form = LoginTraditionalForm()
        register_form = UserCreateForm()

        if 'invited' in request.POST["form"]:
            self.request.session['invited'] = True
            return redirect(reverse("complaint:create_complaint_last_step"))
        elif 'register' in request.POST["form"]:
            register_form = UserCreateForm(request.POST)
            if register_form.is_valid():
                register_form.save()
                user = authenticate(username=request.POST['username'],
                    password=request.POST['password1'])
                login(request, user)
                return redirect(reverse("complaint:create_complaint_last_step"))
        elif 'login' in request.POST["form"]:
            login_form = LoginTraditionalForm(request.POST)
            if login_form.is_valid():
                user = authenticate(username=request.POST['username'],
                    password=request.POST['password'])
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect(reverse("complaint:create_complaint_last_step"))
                    else:
                        login_error = "* El usuario se encuentra inactivo"
                else:
                    login_error = "* El usuario o contraseña son incorrectos"
        return render(request, 'complaint/create_complaint_last_step.html', {'login_form':login_form,
            'register_form':register_form, 'login_error':login_error,})

class CreateComplaintFinishView(View):
    def get(self, request,  *args, **kwargs):
        return render(request, 'complaint/create_complaint_finish.html')


##
# View Asincronas
##
class MultiUploadAjax(View):
    def post(self, request,  *args, **kwargs):
        if request.is_ajax():
            form = AjaxUploadForm(request.POST, request.FILES)
            if form.is_valid():
                item = form.save()
                if request.FILES.get('image', None):
                    data = {'id':item.id, 'image':item.image.url, }
                else:
                    data = {'id':item.id, 'image':None}

                data_temp = []

templates/complaint/create_complaint_finish.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&appId=731623136870740&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="wrapgeneral">
    <div class="container">
        <div class="row">
        
            <div id="main" class="col-md-8 col-md-offset-2">
                <div class="row">
                    <div class="mt-xxlarge col-md-8 col-md-offset-2">
                        <h1 class="txt-c" style="display: block; height: auto; color: #058f00; font-weight: bold; margin: 0 0 1rem; line-height: 1;">Felicidades!</h1>
                        <p>Tu queja ha sido publicada correctamente, actualmente esta en moderacion.</p>
                    </div>

                    <div class="col-md-4 col-md-offset-4">
                        <div class="box txt-c">
                                <a href="#" class="btn btn-small btn-inline mb-small">
                                    <span class="txt"><i class="fa fa-facebook mrxxs"></i>Comparte con Facebook</span>
                                </a>

                                <a href="#" class="btn btn-small btn-inline mb-small">
                                    <span class="txt"><i class="fa fa-twitter mrxxs"></i>Comparte con Twitter</span>
                                </a>

                                <a href="#" class="btn btn-small btn-inline mb-small">
                                    <span class="txt"><i class="fa fa-google mrxxs"></i>Comparte con Google</span>
                                </a>
                        </div>

                        <p class="txt-c">
                            <a class="mt" href="#"><strong>Ir tu publicacion</strong></a>
                        </p>
                    </div>

                </div>
            </div>
            <!-- main -->
            
        </div>
        <!-- row -->
    </div>
    <!-- container -->
</div>
{% endblock %}

templates/complaint/create_complaint_last_step.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&appId=731623136870740&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="wrapgeneral">
    <div class="container">
        <div class="row">
            <div class="post_header col-md-12">
                <div class="row">
                    <div class="top col-md-8">
                        <h2 class="mt-large mb-none">Tu publicación está casi lista. </h2>
                        <p class="hint mt-small mb-large">Regístrate para obtener los siguientes beneficios.</p>
                    </div>
                </div>
            </div>
        
            <div id="main" class="col-md-8">
                <div class="row">
                    <div class="form-page col-md-12">
                        <ul class="capabilities">
                            <li>
                                <i class="fa fa-check-square-o icon"></i>
                                <strong>Marcar tu queja como solucionada</strong>una vez estés satisfecho con la solución por parte de <span class="rint">{{company}}</span>
                            </li>
                            <li>
                                <i class="fa fa-check-square-o icon"></i>
                                <strong>Actualizar tu queja</strong>Puedes hacer cuantas actualizaciones sean necesarias para solucionar tu problema e inclusive para mantener a tus lectores informados.
                            </li>
                            <li>
                                <i class="fa fa-check-square-o icon"></i>
                                <strong>Obtener notificaciones por email</strong>Acerca de nuevos comentarios de tu queja y respuestas por parte de las empresas.
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-9 mt-large">
                        <div class="text-bar mvm text-bar-center">
                            <span class="text">o</span>
                        </div>

                        <div class="txt-c">
                            <a href="{% url 'social:begin' 'facebook' %}?next={{request.get_full_path}}" class="btn btn-fb">
                                <span class="txt"><i class="fa fa-facebook mrxxs"></i>Ingresar con Facebook</span>
                            </a>

                            <a href="{% url 'social:begin' 'twitter' %}?next={{request.get_full_path}}" class="btn btn-tw">
                                <span class="txt"><i class="fa fa-twitter mrxxs"></i>Ingresar con Twitter</span>
                            </a>

                            <a href="{% url 'social:begin' 'google-oauth2' %}?next={{request.get_full_path}}" class="btn btn-go">
                                <span class="txt"><i class="fa fa-google mrxxs"></i>Ingresar con Google</span>
                            </a>
                        </div>

                        <div class="text-bar mvm text-bar-center">
                            <span class="text">o</span>
                        </div>

                        <ul id="tabs" class="nav nav-tabs nav-justified mb-small">
                      <li class="active"><a href="#login">Login</a></li>
                      <li><a href="#register">Registro</a></li>
                    </ul>
                    <script>
                    $(document).ready(function() {
                        $("#register").hide();

                        $("a[href=\"#register\"]").click(function(event){
                            event.preventDefault();
                            $("a[href=\"#login\"]").parent(".active").removeClass("active");
                            $(this).parent("li").addClass("active");
                            $("#login").fadeOut(100);
                            $("#register").delay(100).fadeIn(100);
                        });

                        $("a[href=\"#login\"]").click(function(event){
                            event.preventDefault();
                            $("a[href=\"#register\"]").parent(".active").removeClass("active");
                            $(this).parent("li").addClass("active");
                            $("#register").fadeOut(100);
                            $("#login").delay(100).fadeIn(100);
                        });
                    });
                    </script>

                    <form method="post" class="login" id="login">{% csrf_token %}
                        {{login_form.form}}
                        <div class="grouped-form">
                            <div class="control-group">
                                <div class="control">
                                    <span class="input bg-brighter">
                                        {{login_form.username}}
                                        <span class="has-error">{{login_form.username.errors.as_text}}</span>
                                    </span>
                                </div>
                            </div>

                            <div class="control-group">
                                <div class="control">
                                    <span class="input bg-brighter">
                                        {{login_form.password}}
                                        <span class="has-error">{{login_form.password.errors.as_text}}</span>
                                    </span>
                                </div>
                            </div>
                            {% if login_error %}
                                <span class="has-error">{{login_error}}</span>
                            {% endif %}
                        </div>

                        <div class="mt-small type-small txt-r">
                            <a href="#">¿Olvidaste tu contraseña?</a>
                        </div>

                        <div class="control-group mt-large mb-none">
                            <div class="control">
                                <input  style="float: left;" value="Iniciar sesión" type="submit" class="btn btn-inline btn-inverse">
                            </div>
                        </div>
                    </form>

                    <form method="post" class="login" id="register">{% csrf_token %}
                        {{register_form.form}}
                        <div class="grouped-form">
                            <div class="control-group">
                                <div class="control">
                                    <span class="input bg-brighter">
                                        {{register_form.username}}
                                        <span class="has-error">{{register_form.username.errors.as_text}}</span>
                                    </span>
                                </div>
                            </div>

                            <div class="control-group">
                                <div class="control">
                                    <span class="input bg-brighter">
                                        {{register_form.email}}
                                        <span class="has-error">{{register_form.email.errors.as_text}}</span>
                                    </span>
                                </div>
                            </div>

                            <div class="control-group">
                                <div class="control">
                                    <span class="input bg-brighter">
                                        {{register_form.password1}}
                                        <span class="has-error">{{register_form.password1.errors.as_text}}</span>
                                    </span>
                                </div>
                            </div>

                            <div class="control-group">
                                <div class="control">
                                    <span class="input bg-brighter">
                                        {{register_form.password2}}
                                        <span class="has-error">{{register_form.password2.errors.as_text}}</span>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="control-group mt-large mb-none">
                            <div class="control">
                                <input style="float: left;" value="Regístrate" type="submit" class="btn btn-inline btn-inverse">
                            </div>
                        </div>
                    </form>
                    <form method="post" style="float: right;">{% csrf_token %}
                        <input id="id_form" name="form" type="hidden" value="invited">
                        <div class="form-page">
                         <ul>
                            <li>
                                <input class="btn btn-inline btn-primary" type="submit" id="submit" name="submit" value="Publicar queja anonima"/>
                            </li>
                        </ul>
                        </div>
                    </form>

                    <p style="clear: both;" class="mt-large txt-c type-smaller type-muted"> Sumándote o ingresando via Facebook, Twitter o Google+, aceptas los <a href="#">términos y condiciones</a> y las <a href="#">reglas de uso</a> de Dequr.com y aceptas recibir mensajes de correo electrónico ocasionalmente sobre campañas en Dequr.com.</p>

                </div>
            </div>
        </div>
            <!-- main -->
            
            <div id="sidebar-left"  class="col-md-4">
                <div class="complaint-box">
                </div>
            </div>
            <!-- sidebar-left -->
        </div>
        <!-- row -->
    </div>
    <!-- container -->
</div>
{% endblock %}